### ISSUE TITLE
patina 1 18 1 error

### ISSUE THREAD

**Issue by XionioXMaster** [MineInAbyss/DeeperWorld#89]
[10:55:37 INFO]: [DeeperWorld] Enabling DeeperWorld v0.4.73
[10:55:37 ERROR]: Error occurred while enabling DeeperWorld v0.4.73 (Is it up to date?)
[10:55:37 ERROR]: Suspected Plugins: 
[10:55:37 ERROR]:       DeeperWorld{enabled,ver=0.4.73,path=plugins/deeperworld-0.4.73-all.jar}
[10:55:37 ERROR]: Exception details below: 
java.lang.NoClassDefFoundError: kotlin/NotImplementedError
        at com.mineinabyss.deeperworld.DeeperWorldPlugin.onEnable(DeeperWorldPlugin.kt:34) ~[deeperworld-0.4.73-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patina-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patina-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patina-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:333) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[patina-1.18.1.jar:git-Paper-"4f577f6"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: kotlin.NotImplementedError
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patina-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patina-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

**Comment by Boy0000** [comment]
Yeah currently none of our plugins will work on 1.18+ as we are still on 1.17 ourselves.
Eventually they will be updated to support this, but it is most likely some NMS change in either [Idofront](https://github.com/MineInAbyss/DeeperWorld) or [Geary](https://github.com/MineInAbyss/Geary) I would assume, without having looked at it too deeply

**Comment by Boy0000** [comment]
@XionioXMaster DeeperWorld should now work on 1.18.x.
If you wanna verify that it does and close the issue 👍
